<script setup lang="ts">
// The owner's name in block lettering, generated by
// scripts/brand/lettering.py. Inlined so it themes with the page's CSS
// variables and is in the first paint.
import larry from '~/assets/brand/larry.svg?raw'

useSeo({
  description: 'Yufan Han: interested in methods that read population history from genomes. Notes on code, genomes, and everyday life.',
  path: '/'
})

const { data: latestPosts } = await useAsyncData('home:latest', () =>
  queryCollection('posts')
    .where('draft', '=', false)
    .order('date', 'DESC')
    .select(...POST_CARD_FIELDS)
    .limit(6)
    .all()
)

const posts = computed(() => latestPosts.value ?? [])
</script>

<template>
  <div class="home-page">
    <!-- No scroll reveal here or on the section head: both are in the first
         viewport, where the reveal's fade would wait for hydration. -->
    <section class="home-hero">
      <div class="home-copy">
        <h1 class="home-title">Interested in methods that read <em>population history</em> from genomes.</h1>
        <p class="home-description">Notes on code, genomes, and everyday life.</p>
        <div class="home-actions">
          <NuxtLink to="/blog" class="home-cta-button">
            Read the blog
            <AppIcon name="arrow-right" :stroke-width="2" />
          </NuxtLink>
        </div>
        <!-- Decorative: the header already names the site. A trusted,
             build-time asset, so v-html is safe here. -->
        <!-- eslint-disable-next-line vue/no-v-html -->
        <div class="name-mark" aria-hidden="true" v-html="larry" />
      </div>
    </section>

    <section class="section-block">
      <div class="section-head">
        <h2>Latest posts</h2>
        <NuxtLink to="/blog" class="text-link">
          View all
          <AppIcon name="arrow-right" />
        </NuxtLink>
      </div>

      <!-- The first row is in the first viewport, where the first cover is
           usually the LCP, so those cards load eagerly and rise from first
           paint like the archive's. Eager, not high priority, so a cover never
           competes with the hero's font. -->
      <div class="post-grid">
        <PostCard
          v-for="(post, index) in posts"
          :key="post.path"
          :post="post"
          :grid-count="posts.length"
          :show-section="true"
          :heading-level="3"
          :cover-loading="index < 3 ? 'eager' : 'lazy'"
          :in-first-view="index < 3"
          :style="{ '--delay': `${index * 0.05}s` }"
        />
      </div>
    </section>

  </div>
</template>
